clientApi:
  advertisedHost: "ziti-controller-minimal1-client.ziti-controller.svc.cluster.local"
  advertisedPort: 443
cert-manager:
  enabled: true
trust-manager:
  enabled: true
  app:
    trust:
      # Match this namespace where you install the chart
      namespace: "ziti-controller"
