rabbitmq:
  # Get the username and password using
  # username:  kubectl get secret rabbit-cluster-default-user -o jsonpath="{.data.username}" | base64 --decode
  # password: kubectl get secret rabbit-cluster-default-user -o jsonpath="{.data.password}" | base64 --decode
  url: rabbitmq
  queue_name: object_detection_result
  username: default_username
  password: default_password

mongodb:
  url: 34.88.207.138
  username: default_username
  password: default_password
